use softblue;

ALTER TABLE ALUNO ADD DATA_NASCIMENTO VARCHAR(10);

ALTER TABLE ALUNO CHANGE DATA_NASCIMENTO NASCIMENTO DATE NULL;

ALTER TABLE aluno ADD INDEX INDEX_teste(nome);
ALTER TABLE INSTRUTOR DROP EMAIL;
ALTER TABLE INSTRUTOR ADD EMAIL VARCHAR(100);




